ASP.NETejemplos/Models/Mascota.cs
using System.ComponentModel.DataAnnotations;

namespace ASP.NETejemplos.Models
{
    public class Mascota
    {
        [Required]
        public string id { get; set; }
        [Required]
        [MaxLength(20)]
        [MinLength(3)]
        public string nombre { get; set; }
        [Required]
        [Range(10, 700)]
        public double precio { get; set; }
        //[EmailAddress] [Url]
        public string imagen { get; set; }
    }
}

ASP.NETejemplos/Controllers/MascotaController.cs
using ASP.NETejemplos.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.IO;
using Microsoft.AspNetCore.Hosting;
using System.Collections.Generic;
using ASP.NETejemplos.Helpers;

namespace ASP.NETejemplos.Controllers
{
    public class MascotaController : Controller
    {
        private IWebHostEnvironment ihostingEnvironment;
        public MascotaController(IWebHostEnvironment ihostingEnvironment) {
            this.ihostingEnvironment = ihostingEnvironment;
        }
        public IActionResult Index()
        {

            return View("Index", new Mascota());
        }
        public IActionResult IndexMulti()
        {

            return View("IndexMulti", new MascotaMulti());
        }
        [HttpPost]
        public IActionResult Guardar(Mascota m, IFormFile img)
        {
            if (!ModelState.IsValid)
                return View("Index");
            if (img == null || img.Length == 0)
                return Content("Debe subir una imagen!!!");
            else
            {
                string ubicacion = Path.Combine(ihostingEnvironment.WebRootPath, "imagenes", img.FileName);// C:\Usuarios\proy\wwwroot\imagenes\perrito.jpg
                var stream = new FileStream(ubicacion, FileMode.Create);
                img.CopyToAsync(stream);
                m.imagen = img.FileName;// perrito.jpg
            }
            ViewBag.mascota = m;
            return View("Registrado");
        }

        [HttpPost]
        public IActionResult GuardarMultiple(MascotaMulti m, IFormFile[] imgs)
        {
            if (imgs == null || imgs.Length == 0)
                return Content("Debe subir por lo menos una imagen!!!");
            else
            {
                m.imagenes = new List<string>();
                foreach (IFormFile img in imgs) {
                    string ubicacion = Path.Combine(ihostingEnvironment.WebRootPath, "imagenes", img.FileName);// C:\Usuarios\proy\wwwroot\imagenes\perrito.jpg
                    var stream = new FileStream(ubicacion, FileMode.Create);
                    img.CopyToAsync(stream);
                    m.imagenes.Add(img.FileName);// perrito.jpg
                }
            }
            ViewBag.mascotas = m;
            return View("RegistradoMulti");
        }

        public IActionResult ManejoSesion()
        {
            HttpContext.Session.SetInt32("edad", 4);
            HttpContext.Session.SetString("apellido","Perales");
            Mascota ms = new Mascota
            {
                id="444",
                nombre="Pepi",
                precio=45,
                imagen="uno.jpeg"
            };
            SessionHelper.setObjetoToJson(HttpContext.Session, "mascota", ms);

            List<Mascota> mascotas = new List<Mascota>()
            {
                new Mascota
                {
                    id = "111",
                    nombre = "Anni",
                    precio = 50,
                    imagen = "tres.jpeg"
                },
                new Mascota
                {
                    id = "222",
                    nombre = "Noni",
                    precio = 60,
                    imagen = "dos.jpeg"
                },
                new Mascota
                {
                    id = "333",
                    nombre = "Rambo",
                    precio = 70,
                    imagen = "uno.jpeg"
                }
            };
            SessionHelper.setObjetoToJson(HttpContext.Session, "mascotas", mascotas);
            return View("ManejoSesion");
        }
    }
}

ASP.NETejemplos/Views/Mascota/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@model ASP.NETejemplos.Models.Mascota

<center>
    <form asp-controller="Mascota" asp-action="Guardar" method="post" enctype="multipart/form-data">
        <table>
            <tr>
                <td>Id</td>
                <td><input  type="text" asp-for="id"/></td>
            </tr>
            <tr>
                <td>Nombre</td>
                <td><input type="text" asp-for="nombre"/></td>
            </tr>
            <tr>
                <td>Precio</td>
                <td><input type="text" asp-for="precio"/></td>
            </tr>
            <tr>
                <td>Imagen</td>
                <td><input type="file" name="img" multiple></td>
            </tr>
            <tr>
                <td><input type="submit" value="Registrar"/></td>
                <td></td>
            </tr>
        </table>
    </form>
</center>

ASP.NETejemplos/Views/Mascota/IndexMulti.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@model ASP.NETejemplos.Models.MascotaMulti

<center>
    <form asp-controller="Mascota" asp-action="GuardarMultiple" method="post" enctype="multipart/form-data">
        <table>
            <tr>
                <td>Id</td>
                <td><input  type="text" asp-for="id"/></td>
            </tr>
            <tr>
                <td>Nombre</td>
                <td><input type="text" asp-for="nombre"/></td>
            </tr>
            <tr>
                <td>Precio</td>
                <td><input type="text" asp-for="precio"/></td>
            </tr>
            <tr>
                <td>Imagen</td>
                <td><input type="file" name="imgs" multiple="multiple"></td>
            </tr>
            <tr>
                <td><input type="submit" value="Registrar"/></td>
                <td></td>
            </tr>
        </table>
    </form>
</center>

ASP.NETejemplos/Views/Mascota/ManejoSesion.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@using Microsoft.AspNetCore.Http;
@using ASP.NETejemplos.Helpers;

<h3>Datos</h3>

Edad: @Context.Session.GetInt32("edad")
<br/>
Apellido: @Context.Session.GetString("apellido")
<br/>

<h3>Mascota</h3>

@{
    Mascota m = SessionHelper.getJsonToObjeto<Mascota>(Context.Session, "mascota");

}

id: @m.id
<br/>
Nombre: @m.nombre
<br/>
Precio: @m.precio
<br/>
Imagen: <img src="~/imagenes/@m.imagen" width="100"/>

@{
    List<Mascota> ms = SessionHelper.getJsonToObjeto<List<Mascota>>(Context.Session, "mascotas");

}

<table border="1">
    <tr>
        <th>ID</th>
        <th>Nombre</th>
        <th>Precio</th>
        <th>Imagen</th>
    </tr>
    @foreach (var mm in ms)
    {
        <tr>
            <td> @mm.id</td>
            <td>@mm.nombre</td>
            <td>@mm.precio</td>
            <td>
                <img src="~/imagenes/@mm.imagen" width="100"/>
            </td>
        </tr>
    }
</table>

ASP.NETejemplos/Views/Mascota/Registrado.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<table border="1">
    <tr>
        <td>ID</td>
        <td>@ViewBag.mascota.id</td>
    </tr>
    <tr>
        <td>Nombre</td>
        <td>@ViewBag.mascota.nombre</td>
    </tr>
    <tr>
        <td>Precio</td>
        <td>@ViewBag.mascota.precio</td>
    </tr>
    <tr>
        <td>Imagen</td>
        <td>
            <img src="~/imagenes/@ViewBag.mascota.imagen" width="150"/>
        </td>
    </tr>
</table>

<a asp-controller="Mascota" asp-action="Index">Volver...</a>

ASP.NETejemplos/Views/Mascota/RegistradoMulti.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}


<br/>
<h3>Mascota muti fotos</h3>

<table border="1">
    <tr>
        <td>ID</td>
        <td>@ViewBag.mascotas.id</td>
    </tr>
    <tr>
        <td>Nombre</td>
        <td>@ViewBag.mascotas.nombre</td>
    </tr>
    <tr>
        <td>Precio</td>
        <td>@ViewBag.mascotas.precio</td>
    </tr>
    <tr>
        <td>Imagen</td>
        <td>
            @foreach(var img in ViewBag.mascotas.imagenes){
                <img src="~/imagenes/@img" width="150"/>
            }
        </td>
    </tr>
</table>

<a asp-controller="Mascota" asp-action="IndexMulti">Volver...</a>