ASP.NETejemplos/Models/Cuenta.cs
using System.Collections.Generic;

namespace ASP.NETejemplos.Models
{
    public class Cuenta
    {
        public int id { get; set; }
        public string usuario { get; set; }
        public string password { get; set; }
        public string descripcion { get; set; }
        public bool casado { get; set; }

        public List<string> lenguajes { get; set; }
        public string genero { get; set; }

        public string cargo { get; set; }
    }
}

ASP.NETejemplos/Controllers/CuentaController.cs
using ASP.NETejemplos.Models;
using ASP.NETejemplos.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using System.Collections.Generic;

namespace ASP.NETejemplos.Controllers
{
    public class CuentaController : Controller
    {
        public IActionResult Index()
        {
            CuentaVM cuentavm = new CuentaVM();
            cuentavm.cuenta = new Cuenta() { id = 304, casado=true, genero="masculino" };
            cuentavm.lenguajes = new List<Lenguaje>() {
                new Lenguaje(){ id="1", nombre="C++", tickeado = false},
                new Lenguaje(){ id="2", nombre="C#", tickeado = true},
                new Lenguaje(){ id="3", nombre="Java", tickeado = false},
                new Lenguaje(){ id="4", nombre="Python", tickeado = true}
            };
            var cargos = new List<Cargo>() {
                new Cargo{id = "c0", nombre="auxiliar"},
                new Cargo{id = "c1", nombre="consultor"},
                new Cargo{id = "c2", nombre="tecnico"}
            };
            cuentavm.cargos = new Microsoft.AspNetCore.Mvc.Rendering.SelectList(cargos, "id", "nombre");
            return View("Index",cuentavm);
        }

        [HttpPost]
        public  IActionResult Guardar(CuentaVM cvm, List<Lenguaje> lenguajes)
        {
            cvm.cuenta.lenguajes = new List<string>();
            foreach(var len in lenguajes)
                if (len.tickeado)
                    cvm.cuenta.lenguajes.Add(len.id);
            ViewBag.c = cvm.cuenta;
            return View("Registrado");
        }

        [HttpPost]
        public IActionResult destino1()
        {
            return View("destino1");
        }
        [HttpPost]
        public IActionResult destino2()
        {
            return View("destino2");
        }
        [HttpPost]
        public IActionResult destino3()
        {
            return View("destino3");
        }

        public IActionResult IndexCuenta()
        {
            return View("IndexCuenta");
        }
        [HttpPost]
        public IActionResult Login(string usuario, string pass)
        {
            if(usuario != null && usuario.Equals("pepe") && pass != null && pass.Equals("123"))
            {
                HttpContext.Session.SetString("user", usuario);
                return View("Bienvenido");
            }
            else
            {
                ViewBag.error = "Credenciales erradas";
                return View("IndexCuenta");
            }
        }

        public IActionResult Logout()
        {
            
                HttpContext.Session.Remove("user");
                return RedirectToAction("IndexCuenta");
            
        }
    }
}

ASP.NETejemplos/Views/Cuenta/Bienvenido.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@using Microsoft.AspNetCore.Http

<h3>Bienvenido</h3>

Ten una buena nocche, @Context.Session.GetString("user")

<a asp-controller="Cuenta" asp-action="logout"> Salir de la cuenta</a>

ASP.NETejemplos/Views/Cuenta/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@model ASP.NETejemplos.ViewModels.CuentaVM

<center>
    <h3>Postulación a cargo</h3>
    <form asp-controller="Cuenta" asp-action="Guardar" method="post">
        <table>
            <tr>
                <td>Usuario</td>
                <td><input asp-for="cuenta.usuario"/></td>
            </tr>
            <tr>
                <td>Contraseña</td>
                <td><input type="password" asp-for="cuenta.password"/></td>
            </tr>
            <tr>
                <td>Descripción</td>
                <td><textarea cols="30" rows="4" asp-for="cuenta.descripcion"></textarea></td>
            </tr>
            <tr>
                <td>Casado(a)</td>
                <td><input type="checkbox" asp-for="cuenta.casado"/></td>
            </tr>
            <tr>
                <td>Genero</td>
                <td>
                    <input type="radio" value="masculino" asp-for="cuenta.genero"/> Masculino
                    <br/>
                    <input type="radio" value="femenino" asp-for="cuenta.genero"/> Femenino
                </td>
            </tr>
            <tr>
                <td>Lenguajes</td>
                <td>
                    @for(var i =0; i <Model.lenguajes.Count;i++){
                        <input type="hidden" asp-for="@Model.lenguajes[i].id"/>
                        <input type="hidden" asp-for="@Model.lenguajes[i].nombre"/>
                        <input type="checkbox" asp-for="@Model.lenguajes[i].tickeado"/> 
                        <label asp-for="@Model.lenguajes[i].id">@Model.lenguajes[i].nombre</label>
                    }
                </td>
            </tr>
            <tr>
                <td>Cargo</td>
                <td>
                    <select asp-for="cuenta.cargo" asp-items="@Model.cargos"></select>
                </td>
            </tr>
            <tr>
                <input type="submit" value="Registrar"/>
                <input type="hidden" asp-for="cuenta.id"/>
            </tr>
        </table>
    </form>

    <br/>

    <h3>Multiples botones submit</h3>
    <form method="post">
        <input type="submit" value="Al ddestino 1" asp-controller="Cuenta" asp-action="destino1"/><br/>
        <input type="submit" value="Al ddestino 2" asp-controller="Cuenta" asp-action="destino2"/><br/>
        <input type="submit" value="Al ddestino 3" asp-controller="Cuenta" asp-action="destino3"/><br/>
    </form>
</center>

ASP.NETejemplos/Views/Cuenta/IndexCuenta.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<form asp-controller="Cuenta" asp-action="Login" method="post">
    <table>
        <tr>
            <td>Usuario:</td>
            <td><input type="text" name="usuario"/></td>
        </tr>
        <tr>
            <td>Contraseña:</td>
            <td><input type="password" name="pass"/></td>
        </tr>
        <tr>
            <td></td>
            <td><input type="submit" value="Ingresar"/></td>
        </tr>
    </table>

    @ViewBag.error
</form>

ASP.NETejemplos/Views/Cuenta/Registrado.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<table border="1">
    <tr>
        <td>id</td>
        <td>@ViewBag.c.id</td>
    </tr>
    <tr>
        <td>nombre</td>
        <td>@ViewBag.c.usuario</td>
    </tr>
    <tr>
        <td>password</td>
        <td>@ViewBag.c.password</td>
    </tr>
    <tr>
        <td>descripción</td>
        <td>@ViewBag.c.descripcion</td>
    </tr>
    <tr>
        <td>casado</td>
        <td>@ViewBag.c.casado</td>
    </tr>
    <tr>
        <td>Genero</td>
        <td>@ViewBag.c.genero</td>
    </tr>
    <tr>
        <td>Cargo</td>
        <td>@ViewBag.c.cargo</td>
    </tr>
    <tr>
        <td>Lenguajes</td>
        <td>
            @foreach(var len in ViewBag.c.lenguajes)
            {
                <p>>@len</p><br/>
            }
        </td>
    </tr>
</table>

ASP.NETejemplos/Views/Cuenta/destino1.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<a asp-controller="Cuenta" asp-action="Index">Volver</a>

ASP.NETejemplos/Views/Cuenta/destino2.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<a asp-controller="Cuenta" asp-action="Index">Volver</a>

ASP.NETejemplos/Views/Cuenta/destino3.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<a asp-controller="Cuenta" asp-action="Index">Volver</a>