ASP.NETejemplos/Controllers/QueriesStringController.cs
using Microsoft.AspNetCore.Mvc;

namespace ASP.NETejemplos.Controllers
{
    public class QueriesStringController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Index2([FromQuery(Name ="v")] string video)
        {
            ViewBag.video = video;
            return View("index2");
        }
        public IActionResult Index3([FromQuery(Name = "v2")] string video, [FromQuery(Name ="t")] int segundos)
        {
            ViewBag.video = video;
            ViewBag.tiempo = segundos;
            return View("index3");
        }

        public IActionResult Index4()
        {
            string vid = HttpContext.Request.Query["v2"].ToString();
            int seg = int.Parse(HttpContext.Request.Query["t"].ToString());
            ViewBag.video = vid;
            ViewBag.tiempo = seg;
            return View("index4");
        }
    }
}

ASP.NETejemplos/Views/QueriesString/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<div>
    <h3>Los enlaces</h3>
    <br/>
    <a asp-controller="QueriesString" asp-action="Index2" asp-route-v="333xyz">Index 2</a><br/>
    <a asp-controller="QueriesString" asp-action="Index3" asp-route-v2="123abc" asp-route-t="123">Index 3</a><br/>
    <a asp-controller="QueriesString" asp-action="Index4" asp-route-v2="xx70" asp-route-t="777">Index 4</a><br/>
</div>

ASP.NETejemplos/Views/QueriesString/index2.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<center>
    video: @ViewBag.video
</center>

ASP.NETejemplos/Views/QueriesString/index3.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<center>
    video: @ViewBag.video
    tiempo: @ViewBag.tiempo
</center>

ASP.NETejemplos/Views/QueriesString/index4.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<center>
    video: @ViewBag.video
    <br/>
    tiempo: @ViewBag.tiempo
</center>